// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRvQQMPBR-PW68q3O_OfRJLSVPlxKfp7k',
    appId: '1:453291235022:web:56eccb2c1c1c752365e29f',
    messagingSenderId: '453291235022',
    projectId: 'testflutterfi',
    authDomain: 'testflutterfi.firebaseapp.com',
    storageBucket: 'testflutterfi.firebasestorage.app',
    measurementId: 'G-21BSF4MBNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGiy0hx9xj9VatVgaYAoeaP939f_f6tc',
    appId: '1:453291235022:android:ec415ea3949cac8f65e29f',
    messagingSenderId: '453291235022',
    projectId: 'testflutterfi',
    storageBucket: 'testflutterfi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPULFfwySAW6YcI3Yu1Whc1Q4-ChDdmaQ',
    appId: '1:453291235022:ios:ea83079bd8268ce665e29f',
    messagingSenderId: '453291235022',
    projectId: 'testflutterfi',
    storageBucket: 'testflutterfi.firebasestorage.app',
    iosBundleId: 'com.example.testFlutterFi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPULFfwySAW6YcI3Yu1Whc1Q4-ChDdmaQ',
    appId: '1:453291235022:ios:ea83079bd8268ce665e29f',
    messagingSenderId: '453291235022',
    projectId: 'testflutterfi',
    storageBucket: 'testflutterfi.firebasestorage.app',
    iosBundleId: 'com.example.testFlutterFi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRvQQMPBR-PW68q3O_OfRJLSVPlxKfp7k',
    appId: '1:453291235022:web:414115d343efc2fc65e29f',
    messagingSenderId: '453291235022',
    projectId: 'testflutterfi',
    authDomain: 'testflutterfi.firebaseapp.com',
    storageBucket: 'testflutterfi.firebasestorage.app',
    measurementId: 'G-74TQCDF82N',
  );
}
